### ISSUE TITLE
Import Issues "munkres"

### ISSUE THREAD

**Issue by ztrglider** [Jacobe2169/GMatch4py#15]
Having trouble importing gmatch4py.  Looks like there's a deeper problem importing the munkres package.  I've installed it with ```pip install munkres``` and it installed fine.   Trying to install if from ```https://github.com/jfrelinger/cython-munkres-wrapper``` as suggested in the error report prompts an error about not being about to detect the archive format.

What am I doing wrong?

User entry:
```
C:\Users\user>python
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 01:31:54) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmatch4py
```
The error:
```
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\importlib\_bootstrap.py:219: UserWarning: To obtain optimal results install the Cython 'munkres' module at  https://github.com/jfrelinger/cython-munkres-wrapper
  return f(*args, **kwds)
Traceback (most recent call last):
  File "gmatch4py\ged\abstract_graph_edit_dist.pyx", line 13, in gmatch4py.ged.abstract_graph_edit_dist
ImportError: cannot import name munkres

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\gmatch4py\__init__.py", line 4, in <module>
    from .ged.graph_edit_dist import *
  File "gmatch4py\ged\graph_edit_dist.pyx", line 1, in init gmatch4py.ged.graph_edit_dist
  File "gmatch4py\ged\abstract_graph_edit_dist.pyx", line 16, in init gmatch4py.ged.abstract_graph_edit_dist
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\__init__.py", line 390, in <module>
    from .optimize import *
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: The specified module could not be found.
>>>
```

**Comment by Jacobe2169** [comment]
Dear @ztrglider,

As I say in the issue #12, I developed the library for Linux, MacOS due to my work environnement. However, I did not had the time to make it work on windows.

Best,
@Jacobe2169
