### ISSUE TITLE
ModuleNotFoundError: No module named 'gmatch4py.ged.graph_edit_dist'

### ISSUE THREAD

**Issue by Sciss** [Jacobe2169/GMatch4py#19]
Hi there! Thanks for making this project. I'm following the setup in the README, but something is wrong. I installed using `pip3 install .`, then I run `python3`, at the prompt I type

```
>>> # Gmatch4py use networkx graph 
... import networkx as nx 
>>> # import the GED using the munkres algorithm
... import gmatch4py as gm
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/hhrutz/Documents/devel/GMatch4py/gmatch4py/__init__.py", line 4, in <module>
    from .ged.graph_edit_dist import *
ModuleNotFoundError: No module named 'gmatch4py.ged.graph_edit_dist'
```

**Comment by Sciss** [comment]
Ok, if I `cd gmatch4py` before calling `python3`, the import works.
